### ISSUE TITLE
graph target attribute and behavior of inputting quote

### ISSUE THREAD

**Issue by nattaylor** [Smittyvb/ttw#136]
Why does graphs link have a target attribute, forcing it to open in a new tab?

What is the intended behavior of inputing `"`?  It seems not to add the most recent tag.

https://user-images.githubusercontent.com/2789593/104029043-7896ea80-5197-11eb-9927-87ccea996db0.mov

**Comment by Smittyvb** [comment]
> Why does graphs link have a target attribute, forcing it to open in a new tab?

Not any reason in particular, I just thought it would be better for graphs to be in a separate tab.

> What is the intended behavior of inputing `"`? It seems not to add the most recent tag.

It _should_ be adding the last fully answered ping (not the last one in the list). That behaviour is a bit confusing though -- I think I'll change that to some more understandable logic.

**Comment by nattaylor** [comment]
@Smittyvb Once I understood how `"` worked I was happy with it.

The new tab annoying me because I was using ttw as a PWA.

However, I have ceased tracking me time, so don't worry about me.
