### ISSUE TITLE
API: manage conflicting pings

### ISSUE THREAD

**Issue by mykter** [Smittyvb/ttw#287]
I'm thinking about adding the ttw API as a backend for https://github.com/mykter/TagTime-desktop. Let me know if this isn't a use case you want to support!

The current approach of overwriting any pings included in the API request seems like it will work fine with a single client, but will lead to data loss with multiple clients.

There's lots of ways we could handle this. Some initial thoughts on options:
 1. Require clients to implement the merging logic - first they get pings in the range they're about to submit, then they make decisions based on that to decide what pings to submit. Doesn't require any changes to the API. Likely to lead to bugs (different clients doing it wrong), and inefficient.
 2. Have a single global "afk" ping defined for the user at any given time, and require clients to use that (they can update it too). When submitting pings, the server will not overwrite any existing non-afk pings. Reasonably straightforward. There are some sharp edge cases when the afk tag changes for example, you changed the AFK tags then a client for some reason re-submitted its entire local ping database.
 3. On the server side, have separate logs for each client, so submission is the same as it is now. Retrieval involves some kind of merging of the pings from different devices. The most flexible, as it opens the door to the user manually resolving collisions (on top of automated precedence based on afk or not). Sounds like implementations would rapidly become less efficient though - it's no longer a simple database. To address that it could maintain a single "main" log, which is the merger of the individual client logs. No risk of data loss.

Separately it might be helpful to make 'afk' a special kind of datapoint, as opposed to a simple tag. e.g. in the API it could be `null`. This is more complex in some ways (two cases for any given ping), and simpler in others (there's no longer a special tag or combination of tags).

I'd enjoy contributing an implementation after settling on a design.

**Comment by Smittyvb** [comment]
Data loss _should_ only happen if pings are answered differently on two different devices before they sync the other device's ping answer. The server doesn't know or care about pending pings, and only sees them when the user clicks a button to submit the ping (at which point the tags should be finished). Devices only send pings to the server that have been modified locally, so if two devices change two different pings at the same time the server can handle that properly too.

If a user does answer a ping differently on different devices, then it's not clear what they intended: did they mean to overwrite the previous ping or do they want them to be merged? It's not clear.

**Comment by mykter** [comment]
Ah an implicit assumption I was making is that clients automatically create afk pings if you didn't answer. Mine and the original do; I'm assuming other clients do the same.

"Devices only send pings to the server that have been modified locally," -> so in the case of the original client and my client, this is "all pings".

So I guess you're describing a variant of option 1 - require clients to sync before they submit, and do the de-duplication locally?

**Comment by Smittyvb** [comment]
Yes, if a client doesn't keep track of what pings have been modified locally it would need to do merging locally.

**Comment by mykter** [comment]
Are you interested in adding a merging feature server-side? That feels like it would be an important part of any multi-client tagtime server.

**Comment by Smittyvb** [comment]
@mykter I'm still interested in adding such a feature on the server. I do plan on implementing it soon. (although contributions are welcome!)

**Comment by Smittyvb** [comment]
This has now been deployed to ttw.smitop.com. See [the API docs](https://github.com/Smittyvb/ttw/blob/master/docs/api.md#patch-pings) for usage info.
