### ISSUE TITLE
Stopped getting pings

### ISSUE THREAD

**Issue by d3ddd** [Smittyvb/ttw#49]
Hi I started using TagTime Web today and I've been enjoying it. However, after about 2 hours and 10 pings (interval was set around 25min) everything stopped.

In the settings page I saw the note about incorrect ping timing so I updated the interval and reloaded TagTime Web but it's been 1 hour 14.6 minutes and I still haven't gotten any pings. Any suggestions?

I'm using the latest Chrome 85.0.4183.102 on the latest MacOS 10.15.6

**Comment by Smittyvb** [comment]
The settings page probably wasn't clear enough about this here, but the "ping interval" is actually an "average ping interval". The duration between pings is just an average. While on average your pings will be 25 minutes apart, sometimes they will be closer or father apart. I will update the text on the website to be more clear about this. If you're wondering why the interval is random, [this blog post explains it pretty well](http://messymatters.com/tagtime/).

**Comment by d3ddd** [comment]
Oh, ok thanks. With an interval of 25min, waiting 1.5hrs for a ping is a normal amount of randomization?

**Comment by Smittyvb** [comment]
There is a ~97.2% chance that you will wait under 1.5 hours for a ping, and a ~2.8% chance you wait more than 1.5 hours for a ping. You probably just got unlucky. [Math behind this](https://www.desmos.com/calculator/rjxpkotv3o). Although if you go for several hours without a ping it's almost definitely a bug.

**Comment by d3ddd** [comment]
That clears it up very well for me! Also, after 1hr 37min I got a ping so everything's working 👍🏼
